### ISSUE TITLE
噪声数据正确率的测试

### ISSUE THREAD

**Issue by yizx6** [Delver-of-Squeakrets/LISNN#2]
作者您好，请问您是怎么衡量网络对噪声数据的识别正确率？我发现随着模型的训练，网络对于噪声数据的正确率会降低。

**Comment by Delver-of-Squeakrets** [comment]
我们先在不含噪声的数据集上训练，训练完成后分别用带噪和不带噪的测试集进行测试。你观察到的现象（对噪声数据的正确率随训练过程而降低）是正常的，因为含噪数据的分布和不含噪数据的分布是不一致的。

**Comment by yizx6** [comment]
好的，谢谢您的答复！
